{
 "title": "Mikrotik",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mik_system_resource{type=\"uptime\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Current Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mik_system_package_update{type=\"installed-version\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Latest Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mik_system_package_update{type=\"latest-version\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Channel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mik_system_package_update{type=\"channel\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mik_system_package_update{type=\"status\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mik_system_resource{type=\"cpu-load\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CPU Freq",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "mik_system_resource{type=\"cpu-frequency\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "mik_system_resource{type=\"used-memory\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "mik_system_resource{type=\"total-memory\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "HDD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "mik_system_resource{type=\"used-hdd-space\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "mik_system_resource{type=\"total-hdd-space\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "mik_ip_dns{type=\"cache-used\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Records",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_dns_cache{type=\"records\"}",
     "legendFormat": "{{record}}"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mik_interface{type=\"bytes\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bytes Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "mik_interface{type=\"bytes_per_sec\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_interface{type=\"errors\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Wireless", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_interface_wireless{type=\"registered-clients\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CCQ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mik_interface_wireless{type=\"overall-tx-ccq\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Noise Floor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "mik_interface_wireless{type=\"noise-floor\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CCQ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mik_interface_wireless_registration_table{type=\"ccq\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mik_interface_wireless_registration_table{type=\"bytes\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Signal To Noise",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "mik_interface_wireless_registration_table{type=\"signal-to-noise\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "mik_interface_wireless_registration_table{type=\"signal-strength\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Wireguard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mik_interface_wireguard_peers{type=\"bytes\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Firewall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Filter Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_filter{type=\"bytes\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nat Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_nat{type=\"bytes\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Mangle Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_mangle{type=\"bytes\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Raw Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_raw{type=\"bytes\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Address List Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_address_list{type=\"count\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "To VPN Dynamic Domains",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_address_list{type=\"dynamic-to-vpn-domains-list\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Source Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_connection{type=\"src-name-count\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Destination Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_connection{type=\"dst-host-bytes\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_connection{type=\"protocol-count\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FastTrack",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_connection{type=\"fasttrack-count\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Tools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Scheduler Runs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_system_scheduler{type=\"run-count\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Scripts Runs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_system_script{type=\"run-count\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Netwatch",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 146 },
   "targets": [
    { "expr": "mik_tool_netwatch", "legendFormat": "{{comment}}" }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "title": "Topics",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 6, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_log{type=\"topics\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Entries",
   "type": "table",
   "gridPos": { "h": 22, "w": 18, "x": 6, "y": 156 },
   "targets": [
    {
     "expr": "mik_log{type=\"entries\"}",
     "legendFormat": "{{text}}"
    }
   ]
  }
 ]
}